package com.payyourself.trading.beneficiary.tradeBeneficiary;

// Generated Apr 24, 2010 1:54:05 PM by Hibernate Tools 3.2.5.Beta

import com.payyourself.currency.PyCurrency;
import com.payyourself.trading.beneficiary.Beneficiary;

/**
 * TradeBeneficiary generated by hbm2java
 */
public class TradeBeneficiary implements java.io.Serializable {

	private long id;
	private PyCurrency amount;
	private Beneficiary beneficiary;

	public TradeBeneficiary() {
	}

	public TradeBeneficiary(PyCurrency amount, Beneficiary beneficiary) {
		this.amount = amount;
		this.beneficiary = beneficiary;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public PyCurrency getAmount() {
		return this.amount;
	}

	public void setAmount(PyCurrency amount) {
		this.amount = amount;
	}

	public Beneficiary getBeneficiary() {
		return this.beneficiary;
	}

	public void setBeneficiary(Beneficiary beneficiary) {
		this.beneficiary = beneficiary;
	}

}
