package com.payyourself.trading.beneficiary;

// Generated Apr 24, 2010 1:54:05 PM by Hibernate Tools 3.2.5.Beta

import com.payyourself.currency.code.CurrencyCodeEnum;
import com.payyourself.trading.beneficiary.details.BeneficiaryDetails;

/**
 * Beneficiary generated by hbm2java
 */
public class Beneficiary implements java.io.Serializable {

	private long beneficiaryId;
	private String name;
	private CurrencyCodeEnum type;
	private BeneficiaryDetails details;

	public Beneficiary() {
	}

	public Beneficiary(String name, CurrencyCodeEnum type,
			BeneficiaryDetails details) {
		this.name = name;
		this.type = type;
		this.details = details;
	}

	public long getBeneficiaryId() {
		return this.beneficiaryId;
	}

	public void setBeneficiaryId(long beneficiaryId) {
		this.beneficiaryId = beneficiaryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public CurrencyCodeEnum getType() {
		return this.type;
	}

	public void setType(CurrencyCodeEnum type) {
		this.type = type;
	}

	public BeneficiaryDetails getDetails() {
		return this.details;
	}

	public void setDetails(BeneficiaryDetails details) {
		this.details = details;
	}

}
