package com.payyourself.trading.beneficiary.details;

// Generated Apr 24, 2010 1:54:05 PM by Hibernate Tools 3.2.5.Beta

/**
 * AudDetails generated by hbm2java
 */
public class AudDetails extends
		com.payyourself.trading.beneficiary.details.BeneficiaryDetails
		implements java.io.Serializable {

	private String accountNumber;
	private String bsbNumber;

	public AudDetails() {
	}

	public AudDetails(String accountNumber, String bsbNumber) {
		this.accountNumber = accountNumber;
		this.bsbNumber = bsbNumber;
	}

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public String getBsbNumber() {
		return this.bsbNumber;
	}

	public void setBsbNumber(String bsbNumber) {
		this.bsbNumber = bsbNumber;
	}

}
