package com.payyourself.trading.beneficiary.details;

// Generated Apr 24, 2010 1:54:05 PM by Hibernate Tools 3.2.5.Beta

/**
 * UsdDetails generated by hbm2java
 */
public class UsdDetails extends
		com.payyourself.trading.beneficiary.details.BeneficiaryDetails
		implements java.io.Serializable {

	private String accountNumber;
	private String routingNumber;

	public UsdDetails() {
	}

	public UsdDetails(String accountNumber, String routingNumber) {
		this.accountNumber = accountNumber;
		this.routingNumber = routingNumber;
	}

	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public String getRoutingNumber() {
		return this.routingNumber;
	}

	public void setRoutingNumber(String routingNumber) {
		this.routingNumber = routingNumber;
	}

}
