package com.payyourself.trading.chain;

// Generated Apr 24, 2010 1:54:05 PM by Hibernate Tools 3.2.5.Beta

import com.payyourself.trading.trader.group.TraderGroup;

/**
 * TradeLink generated by hbm2java
 */
public class TradeLink implements java.io.Serializable {

	private int linkid;
	private float buyerSellCurrencyMismatch;
	private TraderGroup buyers;
	private TraderGroup sellers;
	private float buyerBuyCurrencyMismatch;

	public TradeLink() {
	}

	public TradeLink(int linkid) {
		this.linkid = linkid;
	}

	public TradeLink(int linkid, float buyerSellCurrencyMismatch,
			TraderGroup buyers, TraderGroup sellers,
			float buyerBuyCurrencyMismatch) {
		this.linkid = linkid;
		this.buyerSellCurrencyMismatch = buyerSellCurrencyMismatch;
		this.buyers = buyers;
		this.sellers = sellers;
		this.buyerBuyCurrencyMismatch = buyerBuyCurrencyMismatch;
	}

	public int getLinkid() {
		return this.linkid;
	}

	public void setLinkid(int linkid) {
		this.linkid = linkid;
	}

	public float getBuyerSellCurrencyMismatch() {
		return this.buyerSellCurrencyMismatch;
	}

	public void setBuyerSellCurrencyMismatch(float buyerSellCurrencyMismatch) {
		this.buyerSellCurrencyMismatch = buyerSellCurrencyMismatch;
	}

	public TraderGroup getBuyers() {
		return this.buyers;
	}

	public void setBuyers(TraderGroup buyers) {
		this.buyers = buyers;
	}

	public TraderGroup getSellers() {
		return this.sellers;
	}

	public void setSellers(TraderGroup sellers) {
		this.sellers = sellers;
	}

	public float getBuyerBuyCurrencyMismatch() {
		return this.buyerBuyCurrencyMismatch;
	}

	public void setBuyerBuyCurrencyMismatch(float buyerBuyCurrencyMismatch) {
		this.buyerBuyCurrencyMismatch = buyerBuyCurrencyMismatch;
	}

}
