package com.payyourself.registration;

// Generated Apr 24, 2010 1:54:05 PM by Hibernate Tools 3.2.5.Beta

/**
 * RegistrationInfo generated by hbm2java
 */
public class RegistrationInfo implements java.io.Serializable {

	private int registrationid;
	private String username;
	private String firstname;
	private String lastname;
	private String password;
	private String email;

	public RegistrationInfo() {
	}

	public RegistrationInfo(String username, String firstname, String lastname,
			String password, String email) {
		this.username = username;
		this.firstname = firstname;
		this.lastname = lastname;
		this.password = password;
		this.email = email;
	}

	public int getRegistrationid() {
		return this.registrationid;
	}

	public void setRegistrationid(int registrationid) {
		this.registrationid = registrationid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(
				Integer.toHexString(hashCode())).append(" [\n");
		buffer.append("username").append("='").append(getUsername()).append(
				"'\n");
		buffer.append("firstname").append("='").append(getFirstname()).append(
				"'\n");
		buffer.append("lastname").append("='").append(getLastname()).append(
				"'\n");
		buffer.append("password").append("='").append(getPassword()).append(
				"'\n");
		buffer.append("]\n");

		return buffer.toString();
	}

}
