package com.payyourself.trading.beneficiary.details;

// Generated Apr 24, 2010 1:54:05 PM by Hibernate Tools 3.2.5.Beta

/**
 * BeneficiaryDetails generated by hbm2java
 */
public class BeneficiaryDetails implements java.io.Serializable {

	private long detailsId;

	public BeneficiaryDetails() {
	}

	public long getDetailsId() {
		return this.detailsId;
	}

	public void setDetailsId(long detailsId) {
		this.detailsId = detailsId;
	}

}
