package com.payyourself.currency.type;

// Generated Apr 24, 2010 1:54:05 PM by Hibernate Tools 3.2.5.Beta

import com.payyourself.currency.code.CurrencyCodeEnum;
import java.util.Calendar;

/**
 * PyCurrencyType generated by hbm2java
 */
public class PyCurrencyType implements java.io.Serializable {

	private long id;
	private CurrencyCodeEnum code;
	private long rateToBase;
	private String symbol;
	private Calendar date;
	private boolean base;

	public PyCurrencyType() {
	}

	public PyCurrencyType(CurrencyCodeEnum code, long rateToBase,
			String symbol, Calendar date) {
		this.code = code;
		this.rateToBase = rateToBase;
		this.symbol = symbol;
		this.date = date;
	}

	public PyCurrencyType(CurrencyCodeEnum code, long rateToBase,
			String symbol, Calendar date, boolean base) {
		this.code = code;
		this.rateToBase = rateToBase;
		this.symbol = symbol;
		this.date = date;
		this.base = base;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public CurrencyCodeEnum getCode() {
		return this.code;
	}

	public void setCode(CurrencyCodeEnum code) {
		this.code = code;
	}

	public long getRateToBase() {
		return this.rateToBase;
	}

	public void setRateToBase(long rateToBase) {
		this.rateToBase = rateToBase;
	}

	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public Calendar getDate() {
		return this.date;
	}

	public void setDate(Calendar date) {
		this.date = date;
	}

	public boolean isBase() {
		return this.base;
	}

	public void setBase(boolean base) {
		this.base = base;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(
				Integer.toHexString(hashCode())).append(" [\n");
		buffer.append("id").append("='").append(getId()).append("'\n");
		buffer.append("code").append("='").append(getCode()).append("'\n");
		buffer.append("rateToBase").append("='").append(getRateToBase())
				.append("'\n");
		buffer.append("symbol").append("='").append(getSymbol()).append("'\n");
		buffer.append("date").append("='").append(getDate()).append("'\n");
		buffer.append("base").append("='").append(isBase()).append("'\n");
		buffer.append("]\n");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PyCurrencyType))
			return false;
		PyCurrencyType castOther = (PyCurrencyType) other;

		return (this.getId() == castOther.getId())
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null
						&& castOther.getCode() != null && this.getCode()
						.equals(castOther.getCode())))
				&& (this.getRateToBase() == castOther.getRateToBase())
				&& ((this.getSymbol() == castOther.getSymbol()) || (this
						.getSymbol() != null
						&& castOther.getSymbol() != null && this.getSymbol()
						.equals(castOther.getSymbol())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null
						&& castOther.getDate() != null && this.getDate()
						.equals(castOther.getDate())))
				&& (this.isBase() == castOther.isBase());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result
				+ (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result + (int) this.getRateToBase();
		result = 37 * result
				+ (getSymbol() == null ? 0 : this.getSymbol().hashCode());
		result = 37 * result
				+ (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (this.isBase() ? 1 : 0);
		return result;
	}

	// The following is extra code specified in the hbm.xml files
	/**
	 * Copy Constructor
	 *
	 */
	public PyCurrencyType(PyCurrencyType original) {
		this.id = original.getId();
		this.code = original.getCode();
		this.rateToBase = original.getRateToBase();
		this.symbol = original.getSymbol();
		this.base = original.isBase();
		this.date = Calendar.getInstance();
		this.date.setTime(original.getDate().getTime());
	}
	// end of extra code specified in the hbm.xml files

}
