package com.payyourself.accounting.product;

// Generated Apr 24, 2010 1:54:05 PM by Hibernate Tools 3.2.5.Beta

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private int id;
	private float fee;
	private boolean active;

	public Product() {
	}

	public Product(float fee, boolean active) {
		this.fee = fee;
		this.active = active;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public float getFee() {
		return this.fee;
	}

	public void setFee(float fee) {
		this.fee = fee;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

}
