package com.payyourself.userManagement.user;

// Generated Apr 24, 2010 1:54:05 PM by Hibernate Tools 3.2.5.Beta

import com.payyourself.trading.beneficiary.Beneficiary;
import java.util.ArrayList;
import java.util.List;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String username;
	private String firstname;
	private String lastname;
	private String password;
	private String email;
	private boolean canTrade;
	private List<Beneficiary> beneficiaries = new ArrayList<Beneficiary>(0);

	public User() {
	}

	public User(String username, String firstname, String lastname,
			String password, String email) {
		this.username = username;
		this.firstname = firstname;
		this.lastname = lastname;
		this.password = password;
		this.email = email;
	}

	public User(String username, String firstname, String lastname,
			String password, String email, boolean canTrade,
			List<Beneficiary> beneficiaries) {
		this.username = username;
		this.firstname = firstname;
		this.lastname = lastname;
		this.password = password;
		this.email = email;
		this.canTrade = canTrade;
		this.beneficiaries = beneficiaries;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean isCanTrade() {
		return this.canTrade;
	}

	public void setCanTrade(boolean canTrade) {
		this.canTrade = canTrade;
	}

	public List<Beneficiary> getBeneficiaries() {
		return this.beneficiaries;
	}

	public void setBeneficiaries(List<Beneficiary> beneficiaries) {
		this.beneficiaries = beneficiaries;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(
				Integer.toHexString(hashCode())).append(" [\n");
		buffer.append("username").append("='").append(getUsername()).append(
				"'\n");
		buffer.append("firstname").append("='").append(getFirstname()).append(
				"'\n");
		buffer.append("lastname").append("='").append(getLastname()).append(
				"'\n");
		buffer.append("password").append("='").append(getPassword()).append(
				"'\n");
		buffer.append("email").append("='").append(getEmail()).append("'\n");
		buffer.append("canTrade").append("='").append(isCanTrade()).append(
				"'\n");
		buffer.append("]\n");

		return buffer.toString();
	}

	// The following is extra code specified in the hbm.xml files
	/**
	 * Copy Constructor
	 * @param user
	 */
	public User(User user) {
		this.username = new String(user.getUsername());
		this.firstname = new String(user.getFirstname());
		this.lastname = new String(user.getLastname());
		this.password = new String(user.getPassword());
		this.setEmail(user.getEmail());
		this.setCanTrade(user.isCanTrade());
	}
	// end of extra code specified in the hbm.xml files

}
