package com.payyourself.accounting.journal;

// Generated Apr 24, 2010 1:54:05 PM by Hibernate Tools 3.2.5.Beta

/**
 * Journal generated by hbm2java
 */
public class Journal implements java.io.Serializable {

	private long id;

	public Journal() {
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(
				Integer.toHexString(hashCode())).append(" [\n");
		buffer.append("id").append("='").append(getId()).append("'\n");
		buffer.append("]\n");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Journal))
			return false;
		Journal castOther = (Journal) other;

		return (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		return result;
	}

}
