package com.payyourself.accounting.account;

// Generated Apr 24, 2010 1:54:05 PM by Hibernate Tools 3.2.5.Beta

import com.payyourself.accounting.account.levelOne.LevelOne;
import com.payyourself.accounting.account.levelTwo.LevelTwo;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private int id;
	private String description;
	private LevelTwo levelTwo;
	private LevelOne levelOne;

	public Account() {
	}

	public Account(String description, LevelTwo levelTwo, LevelOne levelOne) {
		this.description = description;
		this.levelTwo = levelTwo;
		this.levelOne = levelOne;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public LevelTwo getLevelTwo() {
		return this.levelTwo;
	}

	public void setLevelTwo(LevelTwo levelTwo) {
		this.levelTwo = levelTwo;
	}

	public LevelOne getLevelOne() {
		return this.levelOne;
	}

	public void setLevelOne(LevelOne levelOne) {
		this.levelOne = levelOne;
	}

	/**
	 * toString
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(
				Integer.toHexString(hashCode())).append(" [\n");
		buffer.append("id").append("='").append(getId()).append("'\n");
		buffer.append("description").append("='").append(getDescription())
				.append("'\n");
		buffer.append("]\n");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Account))
			return false;
		Account castOther = (Account) other;

		return (this.getId() == castOther.getId())
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());

		return result;
	}

}
