package com.payyourself.trading.tradeGenerator.settings;

// Generated Apr 24, 2010 1:54:05 PM by Hibernate Tools 3.2.5.Beta

/**
 * TaskSettings generated by hbm2java
 */
public class TaskSettings implements java.io.Serializable {

	private long taskId;
	private float allowableMismatch;
	private long computeTradeInterval;
	private float stepSize;
	private int maxGroupSizeBeforeDecimation;
	private String status;
	private boolean run;

	public TaskSettings() {
	}

	public TaskSettings(float allowableMismatch, long computeTradeInterval,
			float stepSize, int maxGroupSizeBeforeDecimation, String status,
			boolean run) {
		this.allowableMismatch = allowableMismatch;
		this.computeTradeInterval = computeTradeInterval;
		this.stepSize = stepSize;
		this.maxGroupSizeBeforeDecimation = maxGroupSizeBeforeDecimation;
		this.status = status;
		this.run = run;
	}

	public long getTaskId() {
		return this.taskId;
	}

	public void setTaskId(long taskId) {
		this.taskId = taskId;
	}

	public float getAllowableMismatch() {
		return this.allowableMismatch;
	}

	public void setAllowableMismatch(float allowableMismatch) {
		this.allowableMismatch = allowableMismatch;
	}

	public long getComputeTradeInterval() {
		return this.computeTradeInterval;
	}

	public void setComputeTradeInterval(long computeTradeInterval) {
		this.computeTradeInterval = computeTradeInterval;
	}

	public float getStepSize() {
		return this.stepSize;
	}

	public void setStepSize(float stepSize) {
		this.stepSize = stepSize;
	}

	public int getMaxGroupSizeBeforeDecimation() {
		return this.maxGroupSizeBeforeDecimation;
	}

	public void setMaxGroupSizeBeforeDecimation(int maxGroupSizeBeforeDecimation) {
		this.maxGroupSizeBeforeDecimation = maxGroupSizeBeforeDecimation;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean isRun() {
		return this.run;
	}

	public void setRun(boolean run) {
		this.run = run;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TaskSettings))
			return false;
		TaskSettings castOther = (TaskSettings) other;

		return (this.getTaskId() == castOther.getTaskId())
				&& (this.getAllowableMismatch() == castOther
						.getAllowableMismatch())
				&& (this.getComputeTradeInterval() == castOther
						.getComputeTradeInterval())
				&& (this.getStepSize() == castOther.getStepSize())
				&& (this.getMaxGroupSizeBeforeDecimation() == castOther
						.getMaxGroupSizeBeforeDecimation())
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus()
						.equals(castOther.getStatus())))
				&& (this.isRun() == castOther.isRun());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getTaskId();
		result = 37 * result + (int) this.getAllowableMismatch();
		result = 37 * result + (int) this.getComputeTradeInterval();
		result = 37 * result + (int) this.getStepSize();
		result = 37 * result + this.getMaxGroupSizeBeforeDecimation();
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (this.isRun() ? 1 : 0);
		return result;
	}

}
